CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS hstore;

CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS osm;

ALTER DATABASE osm SET search_path TO public, osm, app;
ALTER DATABASE osm SET timezone TO 'UTC';